# Versión de la configuración de Docker Compose
version: '3.8'

# Definición de servicios
services:
  documents-services:
    # Configuración para construir la imagen del contenedor
    build:
      context: .
      dockerfile: Dockerfile
    # Nombre de la imagen resultante
    image: sysintegra-documents-image
    # Conexión a la red llamada 'luis'
    networks:
      - luis
    # Mapeo de puertos: Mapea el puerto 6000 del host al puerto 80 del contenedor
    ports:
      - "8000:8000"
    # Nombre del contenedor
    container_name: sysintegra-documents
    # Configuración para reiniciar siempre el contenedor
    restart: always

# Definición de redes
networks:
  # Definición de la red llamada 'luis'
  luis:
    # Especifica que la red es externa (puede haber sido creada fuera de este archivo)
    external: true